# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20161116_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='degree_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('major_name', models.CharField(max_length=30)),
            ],
        ),
    ]
