# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20161122_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='major_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=40, null=True)),
                ('course_id', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
