# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_major_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_enrolled', models.CharField(max_length=30, null=True)),
                ('year_enrolled', models.CharField(max_length=10, null=True)),
                ('major', models.CharField(max_length=20, null=True)),
                ('school', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
