# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
