# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0010_auto_20161124_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='year',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='student_id',
        ),
        migrations.AddField(
            model_name='schedules',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
