# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_delete_co_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free_elective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20, null=True)),
                ('major', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='advisor',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.AlterField(
            model_name='degree_req',
            name='course_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='semester',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
