# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20161130_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='degree_req',
        ),
        migrations.AddField(
            model_name='major_req',
            name='major_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
