# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_auto_20161130_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='major_req',
            new_name='Degree_req',
        ),
    ]
