# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_auto_20161130_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree_req',
            name='major_name',
        ),
    ]
