# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_degree_req_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_req',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.Courses'),
        ),
    ]
