# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_auto_20161130_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_req',
            name='course_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pre_req',
            name='pre_req_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
