# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_auto_20161130_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_advisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
