# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-29 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_auto_20161202_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='id',
            new_name='code',
        ),
    ]
