# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-29 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_auto_20180129_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='course_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
